version: '3'
services:
  postgresql:
    container_name: postgres
    image: postgres:9.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: multitenant
    ports:
      - "5432:5432"
    networks:
      - ms-network
    restart: unless-stopped
networks: 
    ms-network:
        driver: bridge
