CREATE SCHEMA IF NOT EXISTS public;
CREATE SCHEMA IF NOT EXISTS cliente_1;
CREATE SCHEMA IF NOT EXISTS cliente_2;

CREATE TABLE IF NOT EXISTS public.t_person (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS cliente_1.t_person (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS cliente_2.t_person (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL
);